In [81]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [82]:
df = pd.read_csv('hiring.csv')
df.head(10)

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         NaN                    8.0                           9      50000
1         NaN                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    NaN                           7      72000
7        11.0                    7.0                           8      80000

In [83]:
df.columns

Index(['experience', 'test_score(out of 10)', 'interview_score(out of 10)',
       'salary($)'],
      dtype='object')

In [84]:
df.columns = ['experience', 'test_score', 'intervew_score', 'salary']

In [85]:
df.experience = df.experience.fillna(0)
df.experience

0     0.0
1     0.0
2     5.0
3     2.0
4     7.0
5     3.0
6    10.0
7    11.0
Name: experience, dtype: float64

In [86]:
df.test_score = df.test_score.fillna(df.test_score.mean())

In [87]:
df.head(10)

experience  test_score  intervew_score  salary
0         0.0    8.000000               9   50000
1         0.0    8.000000               6   45000
2         5.0    6.000000               7   60000
3         2.0   10.000000              10   65000
4         7.0    9.000000               6   70000
5         3.0    7.000000              10   62000
6        10.0    7.857143               7   72000
7        11.0    7.000000               8   80000

In [88]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience', 'test_score', 'intervew_score']], df.salary)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [89]:
reg.coef_

array([2827.63404314, 1912.93803053, 2196.9753141 ])

In [90]:
reg.intercept_

17237.330313727172

#### Predecimos el valor

##### 2 yr experience, 9 test score, 6 interview score

##### 12 yr experience, 10 test score, 10 interview score

In [91]:
reg.predict([[2,9,6]])

array([53290.89255945])

In [92]:
reg.predict([[12, 10, 10]])

array([92268.07227784])